spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/big_event
    username: root
    password: root
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8080
mybatis:
  mapper-locations: classpath*:com/example/mapper/*.xml
  type-aliases-package: org.example.pojo
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  mapper-locations: classpath*:com/example/mapper/*.xml
  type-aliases-package: org.example.pojo
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
token: Authorization

# --- Static resource mapping for uploaded files ---
# Option A (active, recommended): Java config maps only "/files/**" to the
# physical directory "${user.dir}/files". See:
#   src/main/java/org/example/config/StaticResourceConfig.java
#
# Option B (disabled/commented): Configure global static locations here to also
# include the local files directory. Uncomment to enable, but note this exposes
# the path under the default static handler (pattern usually "/**"), not just
# "/files/**". Prefer Option A if you want precise scoping.
#
# spring:
#   web:
#     resources:
#       static-locations: classpath:/static/, file:${user.dir}/files/
