spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/big_event
    username: root
    password: root
server:
  port: 8080
mybatis:
  mapper-locations: classpath*:com/example/mapper/*.xml
  type-aliases-package: org.example.pojo
  configuration:
    map-underscore-to-camel-case: true
token: Authorization